ENGINE = <<latex_engine>>

build:
<<tab>>$(ENGINE) <<doc_title>>
<<tab>>$(ENGINE) <<doc_title>>
	
clean:
<<tab>>rm -f <<root>>.aux <<root>>.out <<root>>.log <<root>>.pdf <<root>>.nav <<root>>.toc <<root>>.snm